### ISSUE TITLE
Left-over todos

### ISSUE THREAD

**Issue by wehlutyk** [ixxi-dante/nw2vec#33]
- [x] We updated the non-gpu environment in e0b89bc4578d71d80780ec6a0c65163fab6cdce3, so once #29 and #31 have finished running we should update the gpu environment
- [x] Also after #29 has finished running, rename the output files so they include the feature noise scale (as introduced by beba46bad421eb1d7a6a4e3ba1ad45efbfae1d72)
- [x] finish Git-LFS history rewrite for all branches
- [x] recreate a PR to replace #12 which got closed by the history rewrite
- [x] remove `issue-3-mini-batching-with-features` if possible
- [x] remove or check history rewrite of `issue-6-sensitivity-analysis`
- [x] find out git-lfs quota on gitlab.com and on Inria's gitlab, as we are reaching the quota here

**Comment by wehlutyk** [comment]
(Email from GitHub)

We wanted to let you know that you’ve used 80% of your data plan for Git LFS on the organization ixxi-dante. No immediate action is necessary, but you might want to consider purchasing additional data packs to cover your bandwidth and storage usage:

  https://github.com/organizations/ixxi-dante/billing/data/upgrade

Current usage as of 10 Jul 2018 02:31PM UTC:

  Bandwidth: 0.0 GB / 1 GB (0%)
  Storage: 0.96 GB / 1 GB (96%)

**Comment by wehlutyk** [comment]
Git-LFS quotas:
- gitlab.com: 10Go
- gitlab.inria.fr: unknown → [Inria ticket](https://support.inria.fr/SelfService/Display.html?id=110383), [LIP ticket](http://assistance.ens-lyon.fr/front/ticket.form.php?id=79782)

**Comment by wehlutyk** [comment]
Git-LFS on gitlab.inria.fr is not activated because of the lack of a quota system, but that might change as it is a recurring demand.

If the issues/projects on GitLab fit what we have here, I think we could move to gitlab.com once we reach the quota here, then see how to manage files in the future if we hit the 10Go gitlab.com quota. (The other options until Inria has its own server are 1) not versioning data files, 2) using git-annex, but that has poor windows support.)

**Comment by wehlutyk** [comment]
We reached the GitHub LFS quota last Friday, so I move everything to [git-annex](http://git-annex.branchable.com/) with a sort of outsourced storage of the data files in the LIP `/warehouse/COMPLEXNET/nw2vec/annex` folder. Git-annex does sort of the same as git-lfs, just we don't store the data on GitHub. I'll add some doc in the readme to make sure everybody can get started easily.

**Comment by wehlutyk** [comment]
Added a small note to the readme about git-annex. The docs need to be done with someone starting from scratch so we're sure about what to include. We'll do that when needed, so closing this issue as done now.
